"""empty message

Revision ID: a44ed4f8a96b
Revises: 8f8b81403f0a
Create Date: 2022-11-10 05:59:00.445108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44ed4f8a96b'
down_revision = '8f8b81403f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_table('groups_users')
    op.drop_table('reading_lists')
    op.drop_table('books_reading_lists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_reading_lists',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reading_list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('list_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='books_reading_lists_book_id_fkey'),
    sa.ForeignKeyConstraint(['reading_list_id'], ['reading_lists.id'], name='books_reading_lists_reading_list_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'reading_list_id', name='books_reading_lists_pkey')
    )
    op.create_table('reading_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='reading_lists_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reading_lists_pkey')
    )
    op.create_table('groups_users',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='groups_users_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='groups_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name='groups_users_pkey')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    sa.UniqueConstraint('name', name='groups_name_key')
    )
    # ### end Alembic commands ###
