"""empty message

Revision ID: 079434c0a3cf
Revises: 7a347bc7c465
Create Date: 2022-11-06 12:55:45.298750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079434c0a3cf'
down_revision = '7a347bc7c465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_lists')
    # ### end Alembic commands ###
