"""empty message

Revision ID: d537f2001e85
Revises: a59404d68f48
Create Date: 2022-11-06 13:21:18.200797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd537f2001e85'
down_revision = 'a59404d68f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_reading_lists',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('reading_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['reading_list_id'], ['reading_lists.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'reading_list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_reading_lists')
    # ### end Alembic commands ###
