"""empty message

Revision ID: 1828b16638a2
Revises: 769e1981f939
Create Date: 2022-11-19 16:30:11.750913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1828b16638a2'
down_revision = '769e1981f939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_series_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.add_column('books_genres', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.drop_column('books_genres', 'genre_id')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_series_id_fkey', 'books', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###
