"""empty message

Revision ID: bb94d2bbb7f1
Revises: a242be35ba21
Create Date: 2022-11-11 12:08:56.505327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb94d2bbb7f1'
down_revision = 'a242be35ba21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_year', sa.Integer(), nullable=False))
    op.drop_column('books', 'publication_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('books', 'publication_year')
    # ### end Alembic commands ###
