"""empty message

Revision ID: a59404d68f48
Revises: a8bdffcb337a
Create Date: 2022-11-06 13:18:37.183213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59404d68f48'
down_revision = 'a8bdffcb337a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reading_lists', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reading_lists', type_='foreignkey')
    # ### end Alembic commands ###
