"""empty message

Revision ID: 090eb18ea1b8
Revises: c148b2dfc284
Create Date: 2022-11-06 12:43:42.454748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090eb18ea1b8'
down_revision = 'c148b2dfc284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('series_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'series_id')
    # ### end Alembic commands ###
