"""empty message

Revision ID: 47023bc8cebf
Revises: f204be7df96b
Create Date: 2022-11-06 12:32:12.337062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47023bc8cebf'
down_revision = 'f204be7df96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    # ### end Alembic commands ###
