"""empty message

Revision ID: 3497f29a54df
Revises: d537f2001e85
Create Date: 2022-11-06 13:22:17.960979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3497f29a54df'
down_revision = 'd537f2001e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_reading_lists', sa.Column('list_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_reading_lists', 'list_order')
    # ### end Alembic commands ###
