"""empty message

Revision ID: a6151d4853e1
Revises: 38af0e050d11
Create Date: 2022-11-16 20:15:55.584706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6151d4853e1'
down_revision = '38af0e050d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_challenges', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_challenges', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
