"""empty message

Revision ID: 257aafb7d26a
Revises: 
Create Date: 2022-11-06 12:31:35.512436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257aafb7d26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
