"""empty message

Revision ID: 754546ec2cda
Revises: 5bb9af32af9c
Create Date: 2022-11-06 13:15:32.418616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754546ec2cda'
down_revision = '5bb9af32af9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    # ### end Alembic commands ###
