"""empty message

Revision ID: fc26a96901f8
Revises: cbff2087039d
Create Date: 2022-11-06 13:02:13.333004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc26a96901f8'
down_revision = 'cbff2087039d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('series_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'series_order')
    # ### end Alembic commands ###
