"""empty message

Revision ID: a242be35ba21
Revises: a44ed4f8a96b
Create Date: 2022-11-10 12:44:18.009538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a242be35ba21'
down_revision = 'a44ed4f8a96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('ratings', 'rating_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rating_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('ratings', 'created_at')
    # ### end Alembic commands ###
