"""empty message

Revision ID: f41391ad9992
Revises: 2cca451b5317
Create Date: 2022-11-19 15:03:54.079301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41391ad9992'
down_revision = '2cca451b5317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reading_challenges_user_id_fkey', 'reading_challenges', type_='foreignkey')
    op.create_foreign_key(None, 'reading_challenges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reading_challenges', type_='foreignkey')
    op.create_foreign_key('reading_challenges_user_id_fkey', 'reading_challenges', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
