"""empty message

Revision ID: 38af0e050d11
Revises: fc74d2f11992
Create Date: 2022-11-14 12:50:31.641174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38af0e050d11'
down_revision = 'fc74d2f11992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
