"""empty message

Revision ID: 769e1981f939
Revises: b7207f2c7868
Create Date: 2022-11-19 15:18:52.373535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769e1981f939'
down_revision = 'b7207f2c7868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_books_book_id_fkey', 'authors_books', type_='foreignkey')
    op.drop_constraint('authors_books_author_id_fkey', 'authors_books', type_='foreignkey')
    op.create_foreign_key(None, 'authors_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'authors_books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('books_awards_book_id_fkey', 'books_awards', type_='foreignkey')
    op.drop_constraint('books_awards_award_id_fkey', 'books_awards', type_='foreignkey')
    op.create_foreign_key(None, 'books_awards', 'awards', ['award_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books_awards', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('books_genres_genre_id_fkey', 'books_genres', type_='foreignkey')
    op.drop_constraint('books_genres_book_id_fkey', 'books_genres', type_='foreignkey')
    op.create_foreign_key(None, 'books_genres', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books_genres', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_genres', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.create_foreign_key('books_genres_book_id_fkey', 'books_genres', 'books', ['book_id'], ['id'])
    op.create_foreign_key('books_genres_genre_id_fkey', 'books_genres', 'genres', ['genre_id'], ['id'])
    op.drop_constraint(None, 'books_awards', type_='foreignkey')
    op.drop_constraint(None, 'books_awards', type_='foreignkey')
    op.create_foreign_key('books_awards_award_id_fkey', 'books_awards', 'awards', ['award_id'], ['id'])
    op.create_foreign_key('books_awards_book_id_fkey', 'books_awards', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'authors_books', type_='foreignkey')
    op.drop_constraint(None, 'authors_books', type_='foreignkey')
    op.create_foreign_key('authors_books_author_id_fkey', 'authors_books', 'authors', ['author_id'], ['id'])
    op.create_foreign_key('authors_books_book_id_fkey', 'authors_books', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
