"""empty message

Revision ID: 997bfdfc043a
Revises: 754546ec2cda
Create Date: 2022-11-06 13:16:16.142982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997bfdfc043a'
down_revision = '754546ec2cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
